### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dovy** [toekneestuck/edgefonts-preview#3]
Could we use some of this code in a product we sell? Namely a font selector and integration for a CMS.

**Comment by toekneestuck** [comment]
Just added an MIT license. Go for it, and good luck :)

**Comment by dovy** [comment]
Just FYI, found this:

https://edgewebfonts.adobe.com/data/fontData.json

;)

**Comment by toekneestuck** [comment]
@dovy Yeah I had intentions of integrating that data with my previewer, but never got around to it :(
